name: Auto alert to slack

on:
  push:
    branches:
      - main

    paths-ignore:
      - 'Java/복습/**'
      - 'Java/이미지/**'
      - 'git/복습/**'
      - 'git/이미지/**'
      - '.github/**'
      - 'README.md'

jobs:
  auto-alert-to-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            Java
          sparse-checkout-cone-mode: false

      - name: post message to slack
        run: |
          ./script/post-message.sh

      # - uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     text: 'TIL 작성했습니다.'
      #     fields: repo,commit
      #     author_name: 이준혁
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   if: always()