name: Auto alert to slack

on:
  push:
    branches:
      - main

    paths-ignore:
      - 'Java/복습/**'
      - 'Java/이미지/**'
      - 'git/복습/**'
      - 'git/이미지/**'
      - '.github/**'
      - 'README.md'

jobs:
  auto-alert-to-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPOSITORY_URL: ${{github.sha}}
          GITHUB_MESSAGE: ${{github.event.head_commit.message}}
        run: |
          GITHUB_MESSAGE_TR=$("${{github.event.head_commit.message}}" | tr ' ' '%20')
          echo ${GITHUB_MESSAGE_TR}
          # curl -X POST -H 'Content-type: application/json' \
          #  --data '{"text":"<https://github.com/uotoua/TIL/blob/main/Java/${GITHUB_MESSAGE_TR}.md |TEST>"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          # bash script/post-message.sh


      # - name: post message to slack
      #   run: 

      # - uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     text: 'TIL 작성했습니다.'
      #     fields: repo,commit
      #     author_name: 이준혁
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   if: always()