name: Auto alert to slack

on:
  push:
    branches:
      - main

    paths:
      - 'Java/**'

    paths-ignore:
      - 'Java/복습/**'
      - 'Java/이미지/**'

jobs:
  auto-alert-to-slack:
    runs-on: ubuntu-latest

    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,workflow
          author_name: 이준혁
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()